name: Test Self-Reposcope-Action

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    test-action:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout this repo
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Use the action
              uses: ./
              with:
                  github_token: ${{ secrets.REPOSCOPE_TOKEN }}

            - name: Check result file exists
              shell: bash
              run: |
                  test -f ./tools/self-reposcope/output/*.svg && cp -r ./tools/self-reposcope/output . && echo "SVG file generated successfully"
